// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { RatioConfig, RatioConfigData, RatioConfigTableId } from "./tables/RatioConfig.sol";
import { ItemSellerERC20, ItemSellerERC20Data, ItemSellerERC20TableId } from "./tables/ItemSellerERC20.sol";
import { ItemPrice, ItemPriceData, ItemPriceTableId } from "./tables/ItemPrice.sol";
