// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ItemTradeERC20, ItemTradeERC20Data } from "./tables/ItemTradeERC20.sol";
import { ItemTradeTokenSum } from "./tables/ItemTradeTokenSum.sol";
import { ItemPriceInToken, ItemPriceInTokenData } from "./tables/ItemPriceInToken.sol";
import { ItemQuantityMultipleForToken, ItemQuantityMultipleForTokenData } from "./tables/ItemQuantityMultipleForToken.sol";
