// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ItemSellerERC20Data } from "./../tables/ItemSellerERC20.sol";
import { ItemPriceData } from "./../tables/ItemPrice.sol";

/**
 * @title IItemSeller
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IItemSeller {
  function test__registerERC20Token(uint256 smartObjectId, address tokenAddress, address receiver) external;

  function test__updateERC20Receiver(uint256 smartObjectId, address receiver) external;

  function test__getERC20Data(uint256 smartObjectId) external view returns (ItemSellerERC20Data memory);

  function test__setItemPrice(uint256 smartObjectId, uint256 itemId, uint256 price) external;

  function test__unsetItemPrice(uint256 smartObjectId, uint256 itemId) external;

  function test__getItemPriceData(uint256 smartObjectId, uint256 itemId) external view returns (ItemPriceData memory);

  function test__purchaseItem(uint256 smartObjectId, uint256 itemId, uint256 quantity) external;
}
