// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { EntityRecordData, SmartObjectData, WorldPosition } from "@eveworld/world/src/modules/smart-storage-unit/types.sol";
import { InventoryItem } from "@eveworld/world/src/modules/inventory/types.sol";

/**
 * @title IWarEffort
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IWarEffort {
  function test__createAndAnchorWarEffort(
    uint256 smartObjectId,
    EntityRecordData memory entityRecordData,
    SmartObjectData memory smartObjectData,
    WorldPosition memory worldPosition,
    uint256 fuelUnitVolume,
    uint256 fuelConsumptionPerMinute,
    uint256 fuelMaxCapacity,
    uint256 storageCapacity,
    uint256 ephemeralStorageCapacity
  ) external;

  function test__associateSSUToWarEffort(uint256 smartObjectId) external;

  function test__setAcceptedItemTypeId(uint256 smartObjectId, uint256 entityTypeId) external;

  function test__setTargetQuantity(uint256 smartObjectId, uint256 targetItemQuantity) external;

  function test__warEffortEphemeralToInventoryTransferHook(
    uint256 smartObjectId,
    InventoryItem[] memory items
  ) external;

  function test__wareEffortDepositToInventoryHook(uint256 smartObjectId, InventoryItem[] memory items) external;

  function test__warEffortInventoryToEphemeralTransferHook(
    uint256 smartObjectId,
    InventoryItem[] memory items
  ) external;

  function test__warEffortWithdrawFromInventoryHook(uint256 smartObjectId, InventoryItem[] memory items) external;
}
