// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct ItemQuantityMultipleForTokenData {
  bool isSet;
  uint256 enforcedItemMultiple;
  uint256 tokenAmount;
}

library ItemQuantityMultipleForToken {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "test1", name: "ItemQuantityMult", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x746274657374310000000000000000004974656d5175616e746974794d756c74);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0041030001202000000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (uint256, uint256)
  Schema constant _keySchema = Schema.wrap(0x004002001f1f0000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (bool, uint256, uint256)
  Schema constant _valueSchema = Schema.wrap(0x00410300601f1f00000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](2);
    keyNames[0] = "smartObjectId";
    keyNames[1] = "itemInId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](3);
    fieldNames[0] = "isSet";
    fieldNames[1] = "enforcedItemMultiple";
    fieldNames[2] = "tokenAmount";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get isSet.
   */
  function getIsSet(uint256 smartObjectId, uint256 itemInId) internal view returns (bool isSet) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(itemInId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (_toBool(uint8(bytes1(_blob))));
  }

  /**
   * @notice Get isSet.
   */
  function _getIsSet(uint256 smartObjectId, uint256 itemInId) internal view returns (bool isSet) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(itemInId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (_toBool(uint8(bytes1(_blob))));
  }

  /**
   * @notice Set isSet.
   */
  function setIsSet(uint256 smartObjectId, uint256 itemInId, bool isSet) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(itemInId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((isSet)), _fieldLayout);
  }

  /**
   * @notice Set isSet.
   */
  function _setIsSet(uint256 smartObjectId, uint256 itemInId, bool isSet) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(itemInId));

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((isSet)), _fieldLayout);
  }

  /**
   * @notice Get enforcedItemMultiple.
   */
  function getEnforcedItemMultiple(
    uint256 smartObjectId,
    uint256 itemInId
  ) internal view returns (uint256 enforcedItemMultiple) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(itemInId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get enforcedItemMultiple.
   */
  function _getEnforcedItemMultiple(
    uint256 smartObjectId,
    uint256 itemInId
  ) internal view returns (uint256 enforcedItemMultiple) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(itemInId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set enforcedItemMultiple.
   */
  function setEnforcedItemMultiple(uint256 smartObjectId, uint256 itemInId, uint256 enforcedItemMultiple) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(itemInId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((enforcedItemMultiple)), _fieldLayout);
  }

  /**
   * @notice Set enforcedItemMultiple.
   */
  function _setEnforcedItemMultiple(uint256 smartObjectId, uint256 itemInId, uint256 enforcedItemMultiple) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(itemInId));

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((enforcedItemMultiple)), _fieldLayout);
  }

  /**
   * @notice Get tokenAmount.
   */
  function getTokenAmount(uint256 smartObjectId, uint256 itemInId) internal view returns (uint256 tokenAmount) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(itemInId));

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get tokenAmount.
   */
  function _getTokenAmount(uint256 smartObjectId, uint256 itemInId) internal view returns (uint256 tokenAmount) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(itemInId));

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set tokenAmount.
   */
  function setTokenAmount(uint256 smartObjectId, uint256 itemInId, uint256 tokenAmount) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(itemInId));

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((tokenAmount)), _fieldLayout);
  }

  /**
   * @notice Set tokenAmount.
   */
  function _setTokenAmount(uint256 smartObjectId, uint256 itemInId, uint256 tokenAmount) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(itemInId));

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((tokenAmount)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(
    uint256 smartObjectId,
    uint256 itemInId
  ) internal view returns (ItemQuantityMultipleForTokenData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(itemInId));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(
    uint256 smartObjectId,
    uint256 itemInId
  ) internal view returns (ItemQuantityMultipleForTokenData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(itemInId));

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(
    uint256 smartObjectId,
    uint256 itemInId,
    bool isSet,
    uint256 enforcedItemMultiple,
    uint256 tokenAmount
  ) internal {
    bytes memory _staticData = encodeStatic(isSet, enforcedItemMultiple, tokenAmount);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(itemInId));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(
    uint256 smartObjectId,
    uint256 itemInId,
    bool isSet,
    uint256 enforcedItemMultiple,
    uint256 tokenAmount
  ) internal {
    bytes memory _staticData = encodeStatic(isSet, enforcedItemMultiple, tokenAmount);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(itemInId));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(uint256 smartObjectId, uint256 itemInId, ItemQuantityMultipleForTokenData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.isSet, _table.enforcedItemMultiple, _table.tokenAmount);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(itemInId));

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(uint256 smartObjectId, uint256 itemInId, ItemQuantityMultipleForTokenData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.isSet, _table.enforcedItemMultiple, _table.tokenAmount);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(itemInId));

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  ) internal pure returns (bool isSet, uint256 enforcedItemMultiple, uint256 tokenAmount) {
    isSet = (_toBool(uint8(Bytes.getBytes1(_blob, 0))));

    enforcedItemMultiple = (uint256(Bytes.getBytes32(_blob, 1)));

    tokenAmount = (uint256(Bytes.getBytes32(_blob, 33)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (ItemQuantityMultipleForTokenData memory _table) {
    (_table.isSet, _table.enforcedItemMultiple, _table.tokenAmount) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(uint256 smartObjectId, uint256 itemInId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(itemInId));

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(uint256 smartObjectId, uint256 itemInId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(itemInId));

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(
    bool isSet,
    uint256 enforcedItemMultiple,
    uint256 tokenAmount
  ) internal pure returns (bytes memory) {
    return abi.encodePacked(isSet, enforcedItemMultiple, tokenAmount);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    bool isSet,
    uint256 enforcedItemMultiple,
    uint256 tokenAmount
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(isSet, enforcedItemMultiple, tokenAmount);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(uint256 smartObjectId, uint256 itemInId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = bytes32(uint256(smartObjectId));
    _keyTuple[1] = bytes32(uint256(itemInId));

    return _keyTuple;
  }
}

/**
 * @notice Cast a value to a bool.
 * @dev Boolean values are encoded as uint8 (1 = true, 0 = false), but Solidity doesn't allow casting between uint8 and bool.
 * @param value The uint8 value to convert.
 * @return result The boolean value.
 */
function _toBool(uint8 value) pure returns (bool result) {
  assembly {
    result := value
  }
}
